# .github/workflows/main.yml

name: Fetch PoE2 Economy Data

on:
  workflow_dispatch: # Allows you to run the job manually from the Actions tab
  schedule:
    # Runs regularly.
    - cron: "*/20 * * * *"

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    # --- FIX: Add this permissions block ---
    # This grants the GITHUB_TOKEN the permissions to write to the repository.
    permissions:
      contents: write

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Step 2: Set up the Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install the Python libraries
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run the Python script to update the DB
      - name: Run Fetch Data Script
        run: python fetch_data.py

#      - name: Debug analysis
#        run: python debug_currency.py
#
      - name: Run Analysis Script
        run: python analysis.py

      # Step 5: Commit the updated database file
      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          # Add the database, the README, and the new charts folder
          git add *.db README.md charts/ data/
          git status
          git diff --staged --quiet || git commit -m "Update economy data and analysis"
          git push
